import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { SideBar } from "@/components/website/sidebar";
import { Navbar } from "@/components/website/navbar";
import { ScrollArea } from "@/components/ui/scrollarea";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // SemiBold
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased dark`}>
        <main className="flex flex-col w-full h-screen">
          <Navbar />
          <div className="flex flex-row w-full h-full">
            <SideBar />
            <div className="w-[calc(100vw-200px)]">
              <ScrollArea className="h-[calc(100vh-71px)]">
                {children}
              </ScrollArea>
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
